//this file was generated by ChatGPT

let deferredPrompt = null;
const btn = document.getElementById('pwaInstall');

// 1) Eligibility-Event (Chrome/Android)
window.addEventListener('beforeinstallprompt', (e) => {
  e.preventDefault();
  deferredPrompt = e;                  // jetzt „echtes“ Install möglich
  btn.textContent = 'Install app';     // primäre Aktion
});

// 2) Bereits installiert? -> ausblenden
const isStandalone = window.matchMedia('(display-mode: standalone)').matches
                  || window.navigator.standalone === true;
if (isStandalone) btn.style.display = 'none';
window.addEventListener('appinstalled', () => btn.style.display = 'none');

// 3) Snooze respektieren (nicht nerven, aber Button bleibt da)
const snoozeUntil = Number(localStorage.getItem('pwa_install_snooze_until') || 0);
const inSnooze = Date.now() < snoozeUntil;

// 4) Klick-Logik: prompt() wenn möglich, sonst Anleitung (iOS/ohne Event)
btn.addEventListener('click', async () => {
  if (isStandalone) return;

  if (deferredPrompt && !inSnooze) {
    deferredPrompt.prompt();
    const { outcome } = await deferredPrompt.userChoice;
    deferredPrompt = null;
    if (outcome === 'dismissed') {
      // 7 Tage Pause – Button bleibt sichtbar, aber ohne erneutes Prompt
      localStorage.setItem('pwa_install_snooze_until', String(Date.now() + 7*24*60*60*1000));
      btn.textContent = 'Install later';
    } else {
      btn.style.display = 'none';
    }
    return;
  }

  // Kein prompt möglich -> klare Anleitung je Plattform
  if (/iPad|iPhone|iPod/.test(navigator.userAgent)) {
    alert('iOS: Teilen-Icon → „Zum Home-Bildschirm“.');
  } else {
    alert('Öffne das Browser-Menü und wähle „App installieren“.');
  }
  // sanft snoozen, damit du nicht nervst (Button bleibt, aber zeigt wieder Anleitung)
  localStorage.setItem('pwa_install_snooze_until', String(Date.now() + 3*24*60*60*1000));
  btn.textContent = 'How to install';
});
