// This file was generated by chatGPt


// === PWA Install UX – robust, mit/ohne beforeinstallprompt ===
let deferredPrompt = null;
const installBtn = document.getElementById('pwaInstall');

// Helper: Zustände
const isStandalone = window.matchMedia('(display-mode: standalone)').matches
                  || window.navigator.standalone === true; // iOS Safari
const isiOS = () => /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream;
const isSafari = () => /^((?!chrome|android).)*safari/i.test(navigator.userAgent);

// Nicht doppelt einladen
if (!isStandalone) {
  // Button nach kurzer „Engagement“-Phase einblenden (z.B. 3s oder nach „Init Game“-Klick)
  window.addEventListener('load', () => {
    const snooze = localStorage.getItem('pwa_install_snooze_until');
    if (!snooze || Date.now() > Number(snooze)) {
      // iOS zeigt nie beforeinstallprompt -> Button immer zeigen
      // Auf Chrome/Android zeigen wir erstmal auch; ob promptbar ist, prüfen wir beim Klick
      installBtn && (installBtn.style.display = 'block');
    }
  });
}

// Chromium/Android: Event abfangen, um prompt() später auszulösen
window.addEventListener('beforeinstallprompt', (e) => {
  e.preventDefault();
  deferredPrompt = e;
});

// Klick auf Button: entweder prompt() oder Anleitung
installBtn?.addEventListener('click', async () => {
  // Installationsversuch nur bei User-Geste
  if (deferredPrompt) {
    installBtn.disabled = true;
    deferredPrompt.prompt();
    const { outcome } = await deferredPrompt.userChoice;
    deferredPrompt = null;

    if (outcome === 'accepted') {
      installBtn.style.display = 'none';
    } else {
      // Abgelehnt -> z.B. 7 Tage pausieren
      localStorage.setItem('pwa_install_snooze_until', String(Date.now() + 7*24*60*60*1000));
      installBtn.style.display = 'none';
    }
    installBtn.disabled = false;
    return;
  }

  // Kein beforeinstallprompt verfügbar -> Anleitungen je Plattform
  showInstallGuide();
});

// Bereits installiert -> Button weg
window.addEventListener('appinstalled', () => {
  installBtn && (installBtn.style.display = 'none');
});
if (isStandalone) installBtn && (installBtn.style.display = 'none');

// Einfache Anleitung (ersetze alert durch dein eigenes Modal/Toast)
function showInstallGuide() {
  if (isiOS() && isSafari()) {
    alert('iOS: Tippe auf das Teilen-Icon ▶︎ „Zum Home-Bildschirm“.');
    return;
  }

  // Desktop Chrome/Edge/Android (ohne Event): Hinweis aufs Browser-Menü
  alert('Öffne das Browser-Menü und wähle „App installieren“ / „Zum Startbildschirm hinzufügen“.');

  // Optional: nach Hinweis Snooze setzen
  localStorage.setItem('pwa_install_snooze_until', String(Date.now() + 3*24*60*60*1000));
  installBtn.style.display = 'none';
}
